### ISSUE TITLE
Metamask connected to Ethereum mainnet while loading BEP20 token should not produce error

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/ethhmy-bridge.frontend#100]
When I connect metamask to ethereum mainnet and try to load BEP20 token, it produces error.

<img width="1286" alt="Screen Shot 2021-03-28 at 7 57 07 AM" src="https://user-images.githubusercontent.com/13854340/112756752-732d8d00-8f9b-11eb-806d-5cf825483637.png">

If possible, error should not be shown. Even if error needs to be shown, let's point to user that he needs to change the metamask network to BSC.

Error goes away after changing the metamask to BSC.

<img width="1332" alt="Screen Shot 2021-03-28 at 7 56 40 AM" src="https://user-images.githubusercontent.com/13854340/112756788-9f490e00-8f9b-11eb-9dcc-6199ac5c7815.png">

**Comment by potvik** [comment]
Fixed
