### ISSUE TITLE
For Harmony to BSC flow, needs connecting metamask to BSC

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/ethhmy-bridge.frontend#101]
For transferring tokens from Harmony to BSC, connecting the metamask to BSC should not be required? If it is required, at least display the appropriate message like " Change your metamask network to Binance Smart Chain"

<img width="1417" alt="Screen Shot 2021-03-28 at 8 01 32 AM" src="https://user-images.githubusercontent.com/13854340/112756924-38782480-8f9c-11eb-872c-218b4d5211b3.png">

Error goes away, when I change the metamask to BSC:

<img width="1301" alt="Screen Shot 2021-03-28 at 8 02 13 AM" src="https://user-images.githubusercontent.com/13854340/112756914-25fdeb00-8f9c-11eb-82d5-4379bb7d9b8c.png">

**Comment by potvik** [comment]
Fixed
