### ISSUE TITLE
Harmony to BSC bridging using Metamask displays an error at the end, but tx successful

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/ethhmy-bridge.frontend#102]
<img width="1230" alt="Screen Shot 2021-03-28 at 12 40 15 PM" src="https://user-images.githubusercontent.com/13854340/112765711-48efc580-8fc3-11eb-958c-5e3ddd50ce9e.png">

<img width="1166" alt="Screen Shot 2021-03-28 at 12 44 37 PM" src="https://user-images.githubusercontent.com/13854340/112765741-61f87680-8fc3-11eb-8f58-69b51e9d600c.png">

**Comment by potvik** [comment]
Fixed
