### ISSUE TITLE
Remove entries that error out due to trying to bridge non-ERC20 or non-BEP20

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/ethhmy-bridge.frontend#103]
when a user tries to bridge a non-ERC20 or non-BEP20, the operation is error out in the beginning. Such operations can be removed, as they simply make noise in the transaction explorer. 

<img width="1169" alt="Screen Shot 2021-03-29 at 5 29 35 PM" src="https://user-images.githubusercontent.com/13854340/112916008-86804b80-90b4-11eb-9d8e-086d9eee1553.png">

**Comment by potvik** [comment]
Fixed on ui side
