### ISSUE TITLE
disallow inputting bridged contract addresses in place of ONE/ETH wallet address as recipient 

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/ethhmy-bridge.frontend#108]
In spite of clear input label for recipient ONE/ETH wallet address, I see many user inputting bridged contract addresses. This results in loss of funds. We can run a quick check against all bridged assets addresses against the input recipient and warn the user or disallow inputting contract addresses.

<img width="1246" alt="Screen Shot 2021-04-01 at 9 39 19 PM" src="https://user-images.githubusercontent.com/13854340/113381103-ee43ca00-9332-11eb-990b-99633ba3599f.png">

Replicate this for all flows where the recipient input is asked.

**Comment by potvik** [comment]
Done
