### ISSUE TITLE
Tether USD (USDT) from Ethereum is not recognized in the asset explorer, also not marked in the transaction explorer as USDT

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/ethhmy-bridge.frontend#109]
<img width="1153" alt="Screen Shot 2021-04-01 at 9 47 16 PM" src="https://user-images.githubusercontent.com/13854340/113381481-ea647780-9333-11eb-819a-f803931d9f4c.png">

This is the lock tx for the above transfer: https://etherscan.io/tx/0xed3a61b364c589f441b55fdfc2fa17f4ba6e2ff7790b33ca8577f4cc1b8bb3eb

**Comment by gupadhyaya** [comment]
bscUSDT is recognized correctly. only happens for ethereum bridged USDT (1USDT)

**Comment by potvik** [comment]
Fixed
