### ISSUE TITLE
Disallow entering ONE address in place of Hex address (ETH/BSC)

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/ethhmy-bridge.frontend#110]
When bridging from Harmony to ETH (Harmony to BSC), the recipient input field must be limited to hex address only. Currently it allows entering `one` address and automatically converts to hex address. This is dangerous. The bridged tokens may end up in hex addresses (on ETH or BSC) for which the user does not hold the access. Note that, harmony decodes hex address using a different derivation path (from mnemonic) than what ethereum does or other blockchain does.

<img width="1233" alt="Screen Shot 2021-04-02 at 10 54 24 AM" src="https://user-images.githubusercontent.com/13854340/113440820-00108600-93a2-11eb-9e7a-a90f58942d6a.png">

**Comment by potvik** [comment]
Done
