### ISSUE TITLE
[feature] display NFT thumbnail during the bridge process

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/ethhmy-bridge.frontend#131]
We'd like to see a thumbnail of the NFT to be bridged from Ethereum to Harmony or from Harmony to Ethereum as a confirmation.

Right now, I can put the contract address and token id, but it would be better to show a preview of the NFT before I can confirm the bridge transaction to avoid issues.  Otherwise, if I had a typo, I may end up paying gasfee for a wrong transaction.

Also, some more help would be needed for users to figure out how to find the right contract address and token id using etherscan/opensea.

**Comment by jhd2best** [comment]
add the display for name and image of NFT. see https://github.com/harmony-one/ethhmy-bridge.frontend/pull/133
