### ISSUE TITLE
[bridge] auto deposit 1 ONE token to user's account

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/ethhmy-bridge.frontend#136]
when users bridged assets from Ethereum or BSC to Harmony, based on the amount of assets, we shall deposit 1 ONE token to the user's account, so that users can do transactions on Harmony's network, using DEX or something to pay for the gas fee.

My suggestion is to set a parameter in the bridge, like US $100 amount of assets, and deposit 1 ONE to the user's account automatically.

**Comment by jhd2best** [comment]
add new contract for dispatch the ONE token: https://github.com/harmony-one/ethhmy-bridge/pull/5
