### ISSUE TITLE
Add HRC20 contract address in step 1: Register user ERC20 on Harmony in the eth2hmy erc20 flow

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/ethhmy-bridge.frontend#14]
<img width="1235" alt="Screen Shot 2020-10-06 at 12 22 12 PM" src="https://user-images.githubusercontent.com/13854340/95250317-c97cf880-07ce-11eb-8e91-a797e0c78dbd.png">

**Comment by potvik** [comment]
Resolved
