### ISSUE TITLE
Feature Request : Make the labels clickable links, which open up the contract address on explorer

### ISSUE THREAD

**Issue by mirrormirage0** [harmony-one/ethhmy-bridge.frontend#15]
Make "Harmony BUSD", "Harmony LINK" , "Ethereum BUSD", "Ethereum LINK" clickable links, so that its easier to copy the contract address and add to token list in ONE wallet and metamask wallets
![image](https://user-images.githubusercontent.com/29485946/95257518-7e4a0080-0835-11eb-8cc4-bbe3d9e315dd.png)

**Comment by potvik** [comment]
Done
