### ISSUE TITLE
10 BUSD missing 

### ISSUE THREAD

**Issue by err0r711** [harmony-one/ethhmy-bridge.frontend#17]
ETH - HMY

https://kovan.etherscan.io/tx/0xbf3c8e588825ef17305b9a82ba8818c2227be84cadc78ce35a70125a04ec75c0

![screen](https://user-images.githubusercontent.com/31262326/95492438-5d9bbb00-099b-11eb-803e-9c340a78371f.jpg)

had 100 BUSD from faucet

@gupadhyaya 

sorry for opening this this one in frontend instead of backend!

**Comment by potvik** [comment]
![image](https://user-images.githubusercontent.com/57394565/95608111-57721100-0a65-11eb-9a65-bd1ada9cdca6.png)

**Comment by potvik** [comment]
error detected - will resolve in other issue https://github.com/harmony-one/ethhmy-bridge.frontend/issues/25
