### ISSUE TITLE
wait for 13 block confirmation in the harmony to ethereum flow

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/ethhmy-bridge.frontend#18]
currently, we do not force the user wait for 13 blocks confirmation of the unlock transaction in the harmony to Ethereum flow. this could lead to security flaw, where assume the unlock tx succeed, but fail to get finalized (due to forking), then on the harmony side burn happened, but on the Ethereum side unlock didn't, leading to loss of funds. 

could you change to also wait for 13 block confirmation? if confirmation fails, then call revert burn on harmony side to give back user's token.

**Comment by potvik** [comment]
Resolved
