### ISSUE TITLE
remove total BUSD/LINK locked at the right top corner

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/ethhmy-bridge.frontend#19]
I think, since we have the the tokens with all the stats about locked tokens, lets remove the top two numbers.
<img width="1403" alt="Screen Shot 2020-10-09 at 5 31 58 PM" src="https://user-images.githubusercontent.com/13854340/95641147-7cf71e80-0a55-11eb-9e29-c40349225fd8.png">

**Comment by potvik** [comment]
Fixed
