### ISSUE TITLE
step 1 on both eth2hmy and hmy2eth flows seems like needs two tx signing

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/ethhmy-bridge.frontend#29]
after the user signs the first transaction, the progress panel should move to step 2, before asking for signing the second transaction. otherwise, user may think that he is signing two transactions for step 1. 

this problem happens for both the flows.

<img width="1614" alt="Screen Shot 2020-10-10 at 8 49 01 AM" src="https://user-images.githubusercontent.com/13854340/95659459-16feab80-0ad6-11eb-9e5c-52b7cc26188e.png">

<img width="1296" alt="Screen Shot 2020-10-10 at 8 51 48 AM" src="https://user-images.githubusercontent.com/13854340/95659458-1534e800-0ad6-11eb-91b9-01094d116da3.png">

**Comment by potvik** [comment]
Resolved
