### ISSUE TITLE
indicate the user that he will be prompted to sign two transactions (in red color) 

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/ethhmy-bridge.frontend#30]
indicate the user that he will be prompted to sign two transactions (in red color) so that the user will not miss it.
<img width="1280" alt="Screen Shot 2020-10-10 at 8 58 27 AM" src="https://user-images.githubusercontent.com/13854340/95659625-1ca8c100-0ad7-11eb-8815-fcbb15ecf2d8.png">

**Comment by potvik** [comment]
Resolved
