### ISSUE TITLE
throttle the number harmony to ethereum transactions per account

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/ethhmy-bridge.frontend#39]
let us limit the number of harmony to ethereum transactions to 5 per account over 24 hours. basically you need to query all harmony managers (BUSD, LINK, ERC20), getTransactionHistory(manager contract) and then filter using user address and transaction timestamp. If there are already 5 transactions within an hour from the user account (harmony) then disable the frontend.

any other ways?

**Comment by potvik** [comment]
Done https://github.com/harmony-one/ethhmy-bridge.appengine/commit/54356ab5f4060ca8fb06127d4953d328ee81aad2
