### ISSUE TITLE
[critical] the assets explorer shows 0 TVL, probably crashed?

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/ethhmy-bridge.frontend#41]
<img width="1341" alt="Screen Shot 2020-10-14 at 9 27 06 PM" src="https://user-images.githubusercontent.com/13854340/96077255-25e1b700-0e64-11eb-98ee-31edfabe5691.png">

**Comment by gizemcakil** [comment]
I bridged some USDC, it didn't get added to the assets list


![](https://user-images.githubusercontent.com/45907268/96086175-bc1ed880-0e76-11eb-8c78-f109508ed1f4.png)

**Comment by potvik** [comment]
Added Fix
