### ISSUE TITLE
[critical] capture user bumping the transactions 

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/ethhmy-bridge.frontend#42]
currently, if the approve or lock transaction on ethereum takes too long, metamask provides a way to speedup, which creates another transaction with same nonce, but higher gas to make it succeed faster. however, in our backend, we need to take care of this situation. if the original transaction fails due to `dropped & replaced`, then follow the replaced transaction status. this logic needs to fully follow the replacement chain, as a transaction may get bumped several times by the user (if the user is not willing to wait, he may just keep on bumping it). see the attached case:

the operation failed:

<img width="1327" alt="Screen Shot 2020-10-14 at 10 34 29 PM" src="https://user-images.githubusercontent.com/13854340/96081398-0f405d80-0e6e-11eb-9cab-90bbed2208fc.png">

the original transaction was dropped and replaced by the tx below by the user:

<img width="1326" alt="Screen Shot 2020-10-14 at 10 34 41 PM" src="https://user-images.githubusercontent.com/13854340/96081411-123b4e00-0e6e-11eb-8883-ab92651c5818.png">

the replaced transaction succeeded, however our backend could not capture that.

<img width="1291" alt="Screen Shot 2020-10-14 at 10 34 49 PM" src="https://user-images.githubusercontent.com/13854340/96081418-15ced500-0e6e-11eb-8e0b-49c5e8cf3ea3.png">

the logic needs to accommodate regular checking of the transactions whether they are being replaced by some other transactions due to user bumping.

**Comment by potvik** [comment]
Done
