### ISSUE TITLE
[critical] if the transaction fails, don't wait until timeout to report

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/ethhmy-bridge.frontend#43]
if the transaction fails, don't wait until timeout to report. you can regularly check to see if tx has failed and return faster.

<img width="1280" alt="Screen Shot 2020-10-14 at 11 21 05 PM" src="https://user-images.githubusercontent.com/13854340/96084530-18ccc400-0e74-11eb-9ec5-5d72860b451f.png">
<img width="1338" alt="Screen Shot 2020-10-14 at 11 21 16 PM" src="https://user-images.githubusercontent.com/13854340/96084535-19fdf100-0e74-11eb-80e0-97aa981ce65a.png">

**Comment by potvik** [comment]
Resolved
