### ISSUE TITLE
Show information about token contract address or link

### ISSUE THREAD

**Issue by BrunoMarshall** [harmony-one/ethhmy-bridge.frontend#46]
The user need to know the token contract address that the Bridge create for HRC20 tokens, so the user can add the tokens to Onewallet
Also the contracts information should be in the main/front page for:
BUSD in harmony mainnet
LINK in harmony mainnet

![image](https://user-images.githubusercontent.com/35432495/96187678-b809be00-0f3d-11eb-9a2b-014ea3e0d458.png)

**Comment by gupadhyaya** [comment]
this may be little too much and may lead to cluttering of information. the BUSD/LINK contract addresses are already available in the wallets.

**Comment by potvik** [comment]
This Links already added in wallet
