### ISSUE TITLE
Gas used for ETH txs is fixed/low?

### ISSUE THREAD

**Issue by yelllowsin** [harmony-one/ethhmy-bridge.frontend#47]
It seems the bridge is using a fixed or very low gas price of 20 gwei for transactions. The experience is nott that pleasant because i had to bump the gas on Metamask for the txs to get through.

Is it possible to calculate the best gas price to be used at the time the user tries to send the tx? For example, at the time i write this issue the recommended gas price is 50 Gwei for a tx to be confirmed in less than 5 min accordingly to https://ethgasstation.info/

**Comment by gupadhyaya** [comment]
gas price is dynamically fetched using web3.eth.gasPrice api. since the price is quite fluctuating, it is hard sometimes. we will monitor and see if users face major issues before incorporating ethgasstation apis.
