### ISSUE TITLE
Add link to documentation

### ISSUE THREAD

**Issue by gizemcakil** [harmony-one/ethhmy-bridge.frontend#48]
Let's add this text to the 'info' page
"Please find more instructions **here**" and link URL: https://docs.harmony.one/home/showcases/crosschain/horizon-bridge

We can add it right before 'report any issues..' paragraph.
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/45907268/96197115-f7b4b380-0f05-11eb-8983-41c3458a5b2b.png">

**Comment by potvik** [comment]
Done
