### ISSUE TITLE
total locked for tether is not correct

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/ethhmy-bridge.frontend#49]
<img width="1250" alt="Screen Shot 2020-10-16 at 9 26 24 AM" src="https://user-images.githubusercontent.com/13854340/96283938-c386d480-0f91-11eb-921e-cb187fdff6a7.png">
<img width="1308" alt="Screen Shot 2020-10-16 at 9 26 12 AM" src="https://user-images.githubusercontent.com/13854340/96283949-c84b8880-0f91-11eb-86a5-d0f3d4d00535.png">

**Comment by potvik** [comment]
Fixed
