### ISSUE TITLE
[launch-blocker] ERC20 token selector and gif for how to search etherscan for contract address

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/ethhmy-bridge.frontend#50]
lets add a feature for people to select the most popular erc20 tokens for bridging. also create a small clip (gif) showing how to search etherscan for token contract address. 

<img width="1265" alt="Screen Shot 2020-10-16 at 11 38 09 AM" src="https://user-images.githubusercontent.com/13854340/96296927-ee2e5880-0fa4-11eb-88f6-c9af9677cf50.png">

**Comment by potvik** [comment]
ERC20 drop down lost added

**Comment by potvik** [comment]
Done
