### ISSUE TITLE
total locked value in USD

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/ethhmy-bridge.frontend#51]
show total locked value in $ in the top of the https://bridge.harmony.one/tokens page. this could be accomplished by querying etherscan (etherscan api).
for example: https://etherscan.io/address/0x2dCCDB493827E15a5dC8f8b72147E6c4A5620857 shows $521.40 under `token:`. This is for `ETH_ERC20_MANAGER_CONTRACT`. You will also need to query for `ETH_BUSD_MANAGER_CONTRACT` (https://etherscan.io/address/0xfD53b1B4AF84D59B20bF2C20CA89a6BeeAa2c628) and `ETH_LINK_MANAGER_CONTRACT` (https://etherscan.io/address/0xfE601dE9D4295274b9904D5a9Ad7069F23eE2B32) contracts and add the three values to show TVL.

**Comment by potvik** [comment]
Done
