### ISSUE TITLE
transactions page provide ERC20 token contract links

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/ethhmy-bridge.frontend#52]
<img width="1242" alt="Screen Shot 2020-10-17 at 8 07 43 PM" src="https://user-images.githubusercontent.com/13854340/96357787-eeb61480-10b4-11eb-8c5a-02a2478bf6e3.png">

**Comment by gupadhyaya** [comment]
you could also make it like [GST2](https://etherscan.io/token/0x0000000000b3F879cb30FE243b4Dfee438691c04)/[1GST2](https://explorer.harmony.one/#/address/one13c6dzdg7lrds4jkqppmpqa0n85rje46nkxuldu?txType=hrc20)

**Comment by potvik** [comment]
Done
