### ISSUE TITLE
403 when clicking on ERC20 link 

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/ethhmy-bridge.frontend#53]
<img width="1380" alt="Screen Shot 2020-10-18 at 7 25 38 PM" src="https://user-images.githubusercontent.com/13854340/96394825-cfcc8680-1177-11eb-8668-fba070c31cc0.png">

<img width="1907" alt="Screen Shot 2020-10-18 at 7 25 52 PM" src="https://user-images.githubusercontent.com/13854340/96394818-cd6a2c80-1177-11eb-93eb-ad3e95a6beea.png">

**Comment by potvik** [comment]
FIXED
