### ISSUE TITLE
Improvements for 'assets' page: Show total USD value locked and rank accordingly

### ISSUE THREAD

**Issue by gizemcakil** [harmony-one/ethhmy-bridge.frontend#58]
Add a new column for 'total USD value locked' and rank assets from high to low for 'total usd value locked'.

Also, there is an asset that appears twice, not sure what the reason is
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/45907268/96627914-61e2a500-12c6-11eb-9da5-e3a407fe2f43.png">

**Comment by potvik** [comment]
Resolved
