### ISSUE TITLE
check the allowance before asking for user to sign approve tx

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/ethhmy-bridge.frontend#59]
currently if a user has approved previously, the user is still asked to approve again. this may be waste of fee for the user. the front end can simply call `allowance` to check if it is sufficient for the amount that user wants to lock. If so, skip approve and directly go to lock token.
```
function allowance(address _owner, address _spender) public view returns (uint256)
```
Further, we can add a feature for user to select one time large approval amount and later skip approve tx until the allowance is sufficient.
`this feature is not urgent, but quite useful for the user experience`.

**Comment by potvik** [comment]
Done
