### ISSUE TITLE
ONE to ETH flow shows a default 10 'erc20' balance on harmony 

### ISSUE THREAD

**Issue by gizemcakil** [harmony-one/ethhmy-bridge.frontend#60]
I tried with AMPL and POT tokens. I haven't bridged any from Ethereum to harmony yet, but Harmony balance still shows as 10. 
![image](https://user-images.githubusercontent.com/45907268/96756902-923f4780-1389-11eb-8344-211231a0bf66.png)

<img width="1256" alt="image" src="https://user-images.githubusercontent.com/45907268/96756869-881d4900-1389-11eb-899c-7ff6c61aabb2.png">

**Comment by potvik** [comment]
Fixed
