### ISSUE TITLE
TestNFT Bridge - Step 1 status : waiting

### ISSUE THREAD

**Issue by sophoah** [harmony-one/ethhmy-bridge.frontend#64]
I am trying to transfer NFT back from Harmony to ethereum but I am stuck at step 1 User approve bridge to burn token, status : waiting

![image](https://user-images.githubusercontent.com/35721420/104493377-e9168f00-560f-11eb-97fb-abb98f4309a3.png)

**Comment by gupadhyaya** [comment]
@sophoah was signing from one wallet succeed?

**Comment by sophoah** [comment]
@gupadhyaya onewallet never opened, i guess this is something on my client right now since i tried disconnect and reconnect but the one wallet doesn't open. I'll check with a different browser tomorrow

**Comment by potvik** [comment]
@sophoah i had the dsame problem with onewallet.. onewallet seemed to be frozen and did not open for any dapps
I solved this problem by removing the onewallet and installing the latest version

**Comment by sophoah** [comment]
yup that worked thanks
