### ISSUE TITLE
maximum call stack exceeded

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/ethhmy-bridge.frontend#68]
![Untitled](https://user-images.githubusercontent.com/55639830/108833415-15d5a300-75cd-11eb-8bd8-78776be8329f.png)

this looks like a visual bug because the transfer worked, however the approve limited amount tick is a bit dubious, since 111 is already greyed out, i thought at first that im already approving for a limited amount.. which isnt the case

i think we need a better way to show infinite/finite approvals, eg: 

![Untitled1](https://user-images.githubusercontent.com/55639830/108833883-b62bc780-75cd-11eb-8c17-7a48711077d4.png)
![Untitled2](https://user-images.githubusercontent.com/55639830/108833896-ba57e500-75cd-11eb-9942-26a34ec0ebea.png)

**Comment by potvik** [comment]
Should be fixed
