### ISSUE TITLE
BSC Bridge: Autofill ONE address from the BSC Metamask account?

### ISSUE THREAD

**Issue by Dewansahil** [harmony-one/ethhmy-bridge.frontend#73]
<img width="1321" alt="Screen Shot 2021-03-11 at 3 12 08 PM" src="https://user-images.githubusercontent.com/45057123/110867849-53e4ef00-827c-11eb-8ce4-c8f106633e48.png">

**Comment by Dewansahil** [comment]
@potvik

**Comment by potvik** [comment]
Done
