### ISSUE TITLE
Tx fee on the bridge's tx explorer for harmony to eth does not include deposit fee

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/ethhmy-bridge.frontend#77]
<img width="1173" alt="Screen Shot 2021-03-14 at 9 18 55 AM" src="https://user-images.githubusercontent.com/13854340/111075696-7c503180-84a6-11eb-8b53-4e07f1e1d541.png">

**Comment by potvik** [comment]
Resolved
