### ISSUE TITLE
Infinite approval for BSC tokens seems to be not working

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/ethhmy-bridge.frontend#79]
<img width="1237" alt="Screen Shot 2021-03-16 at 10 16 28 PM" src="https://user-images.githubusercontent.com/13854340/111418718-6d839d80-86a5-11eb-8595-f267c2c59342.png">

**Comment by gupadhyaya** [comment]
sometimes work, sometime does not. this should be reliable.

**Comment by gupadhyaya** [comment]
@potvik this is still not working

**Comment by potvik** [comment]
Fixed
