### ISSUE TITLE
quick check for notExecuted before a validator try to confirmTransaction

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/ethhmy-bridge.frontend#85]
currently all validators try to confirmTransaction even on the transactionIds that are already executed due to 2 out of 3 already confirmed. this leads to failure of confirmTransaction, but wasting tx fee. add a check of notExecuted (https://github.com/harmony-one/ethhmy-bridge/blob/master/contracts/lib/MultiSigWallet.sol#L75) call before a validator sends confirmTransaction to save on the tx fee.

**Comment by potvik** [comment]
Done
