### ISSUE TITLE
default fee of 10 Gwei too low for tx to get through

### ISSUE THREAD

**Issue by yelllowsin** [harmony-one/ethhmy-bridge.frontend#86]
Default fee of 10 Gwei sent to Metamask leads to tx timeout after sometime. It works if I change the fas fee manually on metamask to 50 Gwei or higher though.

![telegram-cloud-photo-size-1-5086889206332107284-x](https://user-images.githubusercontent.com/7217595/111631218-e8e26d80-87d1-11eb-909f-a24418521566.jpg)

Step 2 leads to a timeout error after some time has passed.

![image](https://user-images.githubusercontent.com/7217595/111631256-f26bd580-87d1-11eb-9caf-ddc7d705aebb.png)

**Comment by potvik** [comment]
Changed to 100 GWEI for binance testnet
