### ISSUE TITLE
Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by yelllowsin** [harmony-one/ethhmy-bridge.frontend#87]
When trying to bridge from ONE > BSC all the txs complete successfully, but at the end I get this error for USDC.
The assets is transferred successfully though, just this minor error on screen.

![Screenshot at Mar 18 10-20-15](https://user-images.githubusercontent.com/7217595/111632896-b3d71a80-87d3-11eb-835c-48b23825bb7d.png)

**Comment by potvik** [comment]
Fixed
