### ISSUE TITLE
can't use BEP20 custom token address

### ISSUE THREAD

**Issue by sophoah** [harmony-one/ethhmy-bridge.frontend#88]
Tried with testnet BTCB https://testnet.bscscan.com/address/0x6ce8da28e2f864420840cf74474eff5fd80e65b8

here is the error:
![image](https://user-images.githubusercontent.com/35721420/111669215-8630b680-8851-11eb-97f5-de59345539fb.png)

**Comment by potvik** [comment]
FIXED
