### ISSUE TITLE
Bridging new BSC token fails during bridging phase

### ISSUE THREAD

**Issue by JB273** [harmony-one/ethhmy-bridge.frontend#90]
I'm trying to bridge USDT from BSC to Harmony and it fails with a message: `Number can only safely store up to 53 bits`
![image](https://user-images.githubusercontent.com/54506968/111755910-eb0fff00-8899-11eb-8ca9-db0fb650598a.png)

**Comment by JB273** [comment]
Second time when trying it works correctly!
First TX the BNB (~$124) was withdrawn, but no TX succeeded!

**Comment by potvik** [comment]
Fixed
