### ISSUE TITLE
BSC Bridge: Get a RangeError: when selecting a BEP20 token from the list

### ISSUE THREAD

**Issue by JB273** [harmony-one/ethhmy-bridge.frontend#92]
When starting a bridge transaction by using one of the BEP20 tokens from the list I get this error:
![image](https://user-images.githubusercontent.com/54506968/111890933-80240c80-89ee-11eb-9350-09446b75b2fd.png)

didn't have this before...

**Comment by gupadhyaya** [comment]
@JB273 this happens due to exceeding the infura limits. we will probably buy a better service soon.

**Comment by potvik** [comment]
Fixed
