### ISSUE TITLE
UI: add a "$" in front of all the amounts 

### ISSUE THREAD

**Issue by lijiang2087** [harmony-one/ethhmy-bridge.frontend#95]
here

![image](https://user-images.githubusercontent.com/3784595/112090759-66e7a100-8b51-11eb-9ed7-626b300c8b09.png)

and here

![image](https://user-images.githubusercontent.com/3784595/112090777-6ea74580-8b51-11eb-8b2c-fc23e9c24715.png)

**Comment by potvik** [comment]
Fixed
