### ISSUE TITLE
Binance ONE instead of Binance BNB

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/ethhmy-bridge.frontend#96]
<img width="1230" alt="Screen Shot 2021-03-27 at 9 32 16 PM" src="https://user-images.githubusercontent.com/13854340/112742523-1c489900-8f44-11eb-8a24-3dcf9ee67e79.png">

**Comment by gupadhyaya** [comment]
Also this one. 
<img width="1240" alt="Screen Shot 2021-03-27 at 9 36 07 PM" src="https://user-images.githubusercontent.com/13854340/112742577-8f520f80-8f44-11eb-8381-6cee3da2d8e0.png">

**Comment by potvik** [comment]
Fixed
